Name:           ros-kinetic-universal-robot
Version:        1.2.1
Release:        0%{?dist}
Summary:        ROS universal_robot package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/universal_robot
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-kinetic-ur-bringup
Requires:       ros-kinetic-ur-description
Requires:       ros-kinetic-ur-driver
Requires:       ros-kinetic-ur-gazebo
Requires:       ros-kinetic-ur-kinematics
Requires:       ros-kinetic-ur-msgs
Requires:       ros-kinetic-ur10-moveit-config
Requires:       ros-kinetic-ur3-moveit-config
Requires:       ros-kinetic-ur5-moveit-config
BuildRequires:  ros-kinetic-catkin

%description
Drivers, description, and utilities for Universal Robot Arms.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Sat Jan 06 2018 Felix Messmer <fxm@ipa.fhg.de> - 1.2.1-0
- Autogenerated by Bloom

* Fri Aug 04 2017 Felix Messmer <fxm@ipa.fhg.de> - 1.2.0-0
- Autogenerated by Bloom

